### ISSUE TITLE
steps to use the plugin with version 4.24.3

### ISSUE THREAD

**Issue by ilbiffi** [Koderz/RuntimeMeshComponent#161]
Does anyone have a tested step-by-step procedure to have this work in 4.24.3, and/or a compiled version?

**Comment by onirosco** [comment]
I would also like this if possible?

**Comment by ilbiffi** [comment]
I got some replies on discord, version 3 is not officially supported on 4.24 but a guy has posted a version here 
https://cdn.discordapp.com/attachments/455872643174891532/688492266545086541/RMC_3.2_To_UE4.24_changes_1.zip
I didn't try it altough.
Otherwise for version4 use this for, either the master branch or the v4dev
https://github.com/bphelan/RuntimeMeshComponent
By the way this plugin is too messy for my taste...

**Comment by onirosco** [comment]
Hey! Thanks for the reply. And oh really? In what way do you find it messy?

**Comment by ilbiffi** [comment]
214 forks is a good starter, you really have to make experiments, I have downloaded 10 different ue4 versions trying to make this bloody thing work or trying to open the examples.
Plus I've found the same behaviour as with embedded pmc when dealing with collision mesh creation, that means it's not very precise, so as far as my project is concerned it doesn't resolve my problems.

**Comment by Koderz** [comment]
@ilbiffi  Version 4 does support 4.24. Using from GitHub like this will unfortunately require compiling the plugin yourself. I will be updating the marketplace version soon.

Unfortunately the mess of forks was due to me not having the time to maintain the plugin like I wanted for a while, so the community tried to fill in the gaps.

If you have any questions, comments, or suggestions. Feel free to post them here or join the Discord chat and let me know!

-Koderz
