### ISSUE TITLE
Large model support has problems

### ISSUE THREAD

**Issue by myluoxz** [Koderz/RuntimeMeshComponent#43]
When the number of vertices in the model exceeds 7 million faces, the frame rate is very low

**Comment by luoxz** [comment]
Static grid efficiency is very high, RuntimeMesh current vertex number more than 700 million, 980Ti display frame rate as long as 40, static grid 130

**Comment by luoxz** [comment]
7，000，000 Vertex,   FPS： 40

**Comment by Zinglish** [comment]
Is that 7million or 700million? There's a big difference.

As I always ask: show us your code for static grid and RMC please.

**Comment by luoxz** [comment]
RMC:      Vertex:  8,471,687 ;  Mesh: 568 ； FPS: 42
SMC:      Vertex: 7,211,582  ; triangle:   5,135,533 ;     FPS: 150

**Comment by luoxz** [comment]
Code: https://github.com/LaP0573/ue4-fbx-importer
Read the same model,   10,000,000  Vertex,    
StaticMeshComponent：   FPS:   150
RuntimeMeshComponent :  FPS:   42

**Comment by luoxz** [comment]
assimp Library

**Comment by luoxz** [comment]
NVIDIA GeForce GTX980 Ti

**Comment by Koderz** [comment]
That doesn't really surprise me, and there are things coming to v3 to help close this gap but...

To make sure you're getting the most out of what exists... Are you using infrequent update frequency on the sections? Are you using the standard vertex? If so you could do lower precision UVs as you probably don't need the high res UVs. You could also try using the dual buffer sections to get some of the shadowing performance improvement I'll mention below.

Now as for the reasons I'm aware of that there's a speed difference. When you import a static mesh it does a series of "optimizations" to it. First it strips duplicate/degenerate triangles, runs the Forsyth mesh optimizer on it and then it also imports the mesh as 3 separate Vertex buffers. This means if it doesn't need color it doesn't waste the space, and it keeps positions as its own buffer. This usually makes shadowing faster and also base pass faster due to lower required memory bandwidth. If the model is more than one section there's another optimization for shadowing.

RMC v3 should have most of this, but Forsyth would be opt-in as while linear speed it still takes more time than I want to force a section update to take.

**Comment by Koderz** [comment]
Hopefully within 4 weeks. Conservatively 4-8 weeks. Got quite a lot of other things going on right now unfortunately.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
