### ISSUE TITLE
Minimal example for 4.16

### ISSUE THREAD

**Issue by greenmughal** [Koderz/RuntimeMeshComponent#52]
Hi, 
Is there are "Minimal" example for this component, I dont want to derive my own Actor classes, just add my custom component to an emtpy Actor.

**Comment by Koderz** [comment]
Well, the examples show about as simply as you can get how to interact with the RMC, the only difference you'd have for just adding the RMC to your own actor instead of inheriting the other actor  would be to do the following 2 lines in your own actor...
https://github.com/Koderz/RuntimeMeshComponent-Examples/blob/master/Source/RMC_Examples/RuntimeMeshObjectBase.cpp#L14-L15

That will set the RMC up as the root component on the actor, from there those other examples are about as simple as it gets for now.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
