### ISSUE TITLE
Need info on custom vertex structures

### ISSUE THREAD

**Issue by MJLaukala** [Koderz/RuntimeMeshComponent#53]
I 100% need information on custom vertex structures. I probably need info on how to use it with materials as well but I haven't made it that far yet.

**Comment by MJLaukala** [comment]
After more hours of trying to figure this out, DECLARE_RUNTIMEMESH_CUSTOMVERTEX_TYPEINFO and DEFINE_RUNTIMEMESH_CUSTOMVERTEX_TYPEINFO macros under RuntimeMeshCore.h seems to be incomplete. For starters, it's missing the override for FRuntimeMeshVertexTypeInfo::CreateSection(bool bInNeedsPositionOnlyBuffer). Obviously I can write my own class/macro that inherits FRuntimeMeshVertexTypeInfo for my custom vertex type. I'm just concerned about running into more incomplete code. and I'm still not sure if I can use my custom data in materials.

**Comment by Koderz** [comment]
What are you trying to accomplish?   The generic vertex that's built in can handle most possible combinations that the engine can support. With that said there is an issue with the macros for it and defining them in your own module, so you'd have to set that macro within the RMC itself for right now.  Defining completely custom vertex right now is kind of messy due to the structure of what's needed.

 I might do a quick round of fixes for RMCv2 here soon, but RMCv3 is finally moving along pretty quickly, and basically everything gets revamped and drastically improved there.

**Comment by MJLaukala** [comment]
What I am looking to do is to setup custom vertex data that i can use in my materials. I'd have to use the custom material shader node to get access to the extra data in the vertex. I want to use the data to control blending of material functions. I do realize that I probably could use the extra sets of UV coords but I'm trying my best to avoid jankiness.

**Comment by MJLaukala** [comment]
I've only started digging into the core of RMC. I'll try see what it takes to get a working custom vertex structure by the end of the week and let you know what my findings are. Hopefully that will help point you in the right direction as far as implementing something that is clean and stable. I might even try my hand at forking/implementing and submitting a pull request if I have the time.

**Comment by Koderz** [comment]
I'm not sure you can really pass extra components through quite like that, internally the vertex factory registers all the components and their offset from begging of stride and data type  and size. There's options for position, normal, tangent, color and 1-8 UV channels,   While you have the option of changing data types for each of those I haven't seen any options for other channels, Now it would be interesting if it's possible as I've had reasons for dual color channels and other things. I've just never directly looked into that due to having higher priorities on the RMC and well other projects.

If you find anything out, I'd definitely be interested but I will go ahead and warn you there's a complete overhaul to the RMC in the works right now and that entire vertex structure was the first thing to be almost completely rewritten.  It's now cleaner and less buggy with some compilers the previous one had issues with but it's not usable with the old RMC.

**Comment by Koderz** [comment]
Also, I'm in the Unreal Slackers discord ( http://unrealslackers.org/ )
It's generally a faster way to contact me.

**Comment by MJLaukala** [comment]
I did an experiment a few years back and I was able to get custom data to the material using the Custom Material Expression node but i am pretty sure I had to define the extra data location and stride now that i think about it. I didn't do much with the project and wish I still had it. I basically rewrote the entirety of CMC to do it. Do you have a time frame for RMCv3? It's a good thing I'm not too far along into mesh generation with my project.

Just joined the discord.

**Comment by Koderz** [comment]
Hello,

All existing issues for RMCv2 are being closed as RMCv2 is no longer being supported.  RMCv3 is in beta here : https://github.com/Koderz/RuntimeMeshComponent/tree/Version3Dev 

If you encounter this or any new issues in v3 please feel free to open a new issue! 

Thanks!

-Koderz
